# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXvopyfTh-FxCZe_utvgCutQK7n3PLGK
"""



n=int(input())
d=n//86400
ch=(n-(d*86400))//3600
m=((n-d*86400)-ch*3600)//60
print(d,'дней',ch,'часов',m,'минут')
print(n+int(str(n)+str(n))+int(str(n)+str(n)+str(n)))

#8
a,b=float(input()),float(input())
print(a//b)
d,c=int(input()),int(input())
print(d*c)
d,c=int(input()),int(input())
print(d%c)

#7
a,n=int(input()),int(input())
print(a**2//n)

#6
a,b=int(input()),int(input())
print(((a**3+14)/5)*b)

#5
a,b,c=int(input()),int(input()),int(input())
p=a+b+c
s=((p/2)*(p/2-a)*(p/2-b)*(p/2-c))**0.5
print(p,s)

#4
a,b=int(input()),int(input())
print(f'{a}**2+2*{a}*{b}+{b}**2')

#3
a,b=15,10
c=int(input())
print((a+b)//c)

#2
a,b=int(input()),int(input())
print((a+b)**2)

#1
a=5
b=int(input())
print(b*a)